/* Note: Names in this file don't affect routing */
export { default as Event } from '@/events/Event/Event.vue'
export { default as Events } from '@/events/Events/Events.vue'
export { default as EventsCreate } from '@/events/EventsCreate/EventsCreate.vue'
export { default as App } from '@/global/App/App.vue'
export { default as Home } from '@/global/Home/Home.vue'
export { default as NotFound } from '@/global/NotFound/NotFound.vue'
export { default as Heroes } from '@/people/Heroes/Heroes.vue'
export { default as Profile } from '@/people/Profile/Profile.vue'
export { default as Spaces } from '@/views/Spaces/Spaces.vue'
