/* Note: Names in this file don't affect routing */
export { default as Event } from '@/events/Event/Event.vue'
export { default as Events } from '@/events/Events/Events.vue'
export { default as EventsCreate } from '@/events/EventsCreate/EventsCreate.vue'
export { default as App } from '@/views/Global/App.vue'
export { default as Debug } from '@/views/Global/Debug.vue'
export { default as NotFound } from '@/views/Global/NotFound.vue'
export { default as Heroes } from '@/views/Heroes/Heroes.vue'
export { default as Home } from '@/views/Home/Home.vue'
export { default as Profile } from '@/views/Profile/Profile.vue'
export { default as Spaces } from '@/views/Spaces/Spaces.vue'
