name: Build, Test

on:
  pull_request:

jobs:
  Main:
    runs-on: ubuntu-20.04

    steps:
      - name: 'Setup: Node'
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: 'Setup: Git checkout'
        uses: actions/checkout@v2

      - name: 'Setup: Extract branch name'
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: 'Setup: Extract version'
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: 'Setup: Copy cached deps'
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: 'Setup: Install new deps'
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile &> /dev/null

      - name: 'Build: common'
        run: cd common && yarn build

      - name: 'Build: functions'
        run: cd functions && yarn build

      - name: 'Build: hosting'
        run: cd hosting && rm -f .env && yarn build
        env:
          NODE_ENV: production
          VITE_FIREBASE_API_KEY: abcd
          VITE_FIREBASE_APP_ID: 1234
          VITE_FIREBASE_AUTH_DOMAIN: xyz
          VITE_FIREBASE_DATABASE_U_R_L: xyz
          VITE_FIREBASE_MESSAGING_SENDER_ID: 1234
          VITE_FIREBASE_PROJECT_ID: xyz
          VITE_FIREBASE_STORAGE_BUCKET: xyz
          VITE_FUNCTIONS_REGION: xyz
          VITE_BUILD_VERSION: ${{ steps.package-version.outputs.current-version }}

      - name: 'Build: admin'
        run: cd admin && yarn build

      - name: 'Lint: ESLint & Vue'
        run: yarn lint

      - name: 'Test: Execute'
        run: cd common && yarn test:ci

      - name: 'Test: Results reporter'
        uses: tanmen/jest-reporter@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          action-name: 'Tests'
